baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "full stack software engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

    # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating system. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]

[languages]
  [languages.en]
    title = "tarik massac"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "full-stack software engineer"

    [languages.en.params.logo]
      logoText = "cd ~/dev"
      logoHomeLink = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#5500AA"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
    identifier = "resume"
    name       = "resume"
    url        = "/resume"
    weight     = 10
  [[menu.main]]
    identifier = "projects"
    name       = "projects"
    url        = "/projects"  
    weight     = 20

[pagination]
  pagerSize = 10

[params.footer]
  trademark = 2025

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/tmassac/"
[[params.social]]
  name = "github"
  url  = "https://github.com/secondubly/"
[[params.social]]
  name = "email"
  url  = "mailto:tmassac@proton.me"

[caches]
  [caches.images]
    dir = ':cacheDir/images'